### ISSUE TITLE
PHP Fatal error: Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by justinhartman** [Nearata/flarum-ext-embed-video#2]
I'm running a very vanilla Flarum and I enabled your plugin and get a 500 server error when trying to access the front-end. Checking the Nginx log files returns this:

```log
2020/12/16 01:29:50 [error] 9266#9266: *6562 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /var/www/help/vendor/axy/sourcemap/parsing/SegmentParser.php on line 52" while reading response header from upstream, client: 162.158.187.184, server: help, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "help"
```

It doesn't appear to be your plugin as you don't have `axy/sourcemap` linked to your project but it's most certainly conflicting with it.

## Environment

![e5u61FiRcJT7wYiqcgxOg4Wd4QxboiVmEhe9mqNi](https://user-images.githubusercontent.com/717118/102287235-af843280-3f42-11eb-85ff-a517ef8c05e7.jpeg)

- nginx/1.14.2
- PHP-FPM 7.4.13
- Flarum 0.1.0-beta.14.1
- MariaDB 10.3.27

## Composer

```json
{
    "name": "flarum/flarum",
    "description": "Delightfully simple forum software.",
    "type": "project",
    "homepage": "https://flarum.org/",
    "license": "MIT",
    "require": {
        "askvortsov/flarum-categories": "^1.1",
        "bokt/flarum-redis": "^0.1.0",
        "datitisev/flarum-ext-dashboard": "v0.1.0-beta.9.2",
        "flarum/approval": "^0.1.0",
        "flarum/bbcode": "^0.1.0",
        "flarum/core": "^0.1.0",
        "flarum/emoji": "^0.1.0",
        "flarum/flags": "^0.1.0",
        "flarum/lang-english": "^0.1.0",
        "flarum/likes": "^0.1.0",
        "flarum/lock": "^0.1.0",
        "flarum/markdown": "^0.1.0",
        "flarum/mentions": "^0.1.0",
        "flarum/pusher": "^0.1.0",
        "flarum/statistics": "^0.1.0",
        "flarum/sticky": "^0.1.0",
        "flarum/subscriptions": "^0.1.0",
        "flarum/suspend": "^0.1.0",
        "flarum/tags": "^0.1.0",
        "fof/pretty-mail": "^0.2.1",
        "fof/recaptcha": "^0.2.1",
        "fof/sitemap": "^0.5.4",
        "fof/split": "*",
        "fof/upload": "^0.11.3",
        "nearata/flarum-ext-embed-video": "^1.1",
        "v17development/flarum-seo": "^1.4"
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "beta",
    "prefer-stable": true
}
```

**Comment by justinhartman** [comment]
PS. I saw on your forum that you suggested enabling debugging and clearing the cache. Debug mode doesn't help because the site doesn't even resolve a page due to the 500 error and `php flarum cache:clear` doesn't help either.

**Comment by justinhartman** [comment]
Your issue is that you are trying to load a 6.5MB JS map file which is actually not very smart for a site that is in production. Loading `.map` files are fine when you're debugging your code but not for `dist` releases. This should remain in your `src` folder and should not end up in dist.

```console
$ ls -lh vendor/nearata/flarum-ext-embed-video/js/dist/forum.js.map
-rw-r--r-- 1 www-data www-data 6.5M Oct 26 15:30 vendor/nearata/flarum-ext-embed-video/js/dist/forum.js.map
```

Doing this:

```console
$ rm vendor/nearata/flarum-ext-embed-video/js/dist/forum.js.map
-rw-r--r-- 1 www-data www-data 6.5M Oct 26 15:30 vendor/nearata/flarum-ext-embed-video/js/dist/forum.js.map
```

Fixed the 500 error which makes sense because now PHP is no longer trying to load 6.5MB into memory.
Please consider removing the .map for your production releases.

**Comment by Nearata** [comment]
Sorry for the late response and thank you for your tests and solution. I'll publish a new release as soon as possible.
