### ISSUE TITLE
“application/vnd.apple.mpegurl” is not supported

### ISSUE THREAD

**Issue by s1-ranjan** [Nearata/flarum-ext-embed-video#6]
HTTP “Content-Type” of “application/vnd.apple.mpegurl” is not supported. Load of media resource https://nicls1-lh.akamaihd.net/i/lst_1@26969/index_1_av-p.m3u8 failed.

**Comment by Nearata** [comment]
What browser are you using?

**Comment by Nearata** [comment]
Fixed in 2.1.1
