### ISSUE TITLE
unable to show the video to the unlogged user.

### ISSUE THREAD

**Issue by s1-ranjan** [Nearata/flarum-ext-embed-video#7]
It would be nice if there have been some option in the embed code to show or hide videos for the unlogged user, as of now the embed videos are only available to the logged-in user.

**Comment by Nearata** [comment]
Any error in console? The expected behaviour is that anyone can see the videos (this mean guests too). I'm unable to reproduce this issue.

**Comment by s1-ranjan** [comment]
On the Flarum Blog pages, this issue has been observed.

**Comment by Nearata** [comment]
as of today, but added a few releases ago, you can allow/disallow who can watch the videos via global or tag-restricted permissions.

if in need of a different approach, please provide an example
